<a href="https://colab.research.google.com/github/DeepFluxion/Portfolio/blob/main/Notebooks/1_Basico_TensorFlow_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![](https://www.gstatic.com/devrel-devsite/prod/v870be6fb6841f3532cd3aec5bc0b3146031642f2794ae8ba7f51ebf843a655f9/tensorflow/images/lockup.svg)

O TensorFlow é uma plataforma completa de código aberto para machine learning
Com o TensorFlow, iniciantes e usuários avançados podem criar modelos de machine learning com facilidade. Você pode conhecer mais sobre o tensorflow [neste link](https://www.tensorflow.org/).
Este é a primeira parte de uma série de tutoriais para iniciantes começarem sua jornada no tensorflow espero que aproveitem.

A versão 2.0 do Tensorflow foi lançada em 2019, com várias mundanças que simplificaram a execução e a codificação.

Este notebook pode ser executado usando o Google Colab se você nunca o utilzou ante dê uma checada neste [link](https://colab.research.google.com/?utm_source=scs-index)

### Instalando o TensorFlow 2.0

Em geral não é necessário fazer a instalação do tensorflow no colab, pois já você tera sempre a ultima versão estável instalada, mas por algum motivo você pode querer rodar o seu código usando uma versão especifica, por esse motivo vamor ver a sua instalação.

In [1]:
!pip install tensorflow-gpu==2.0.0

     |████████████████████████████████| 380.8 MB 33 kB/s 
     |████████████████████████████████| 50 kB 7.0 MB/s 
     |████████████████████████████████| 3.8 MB 21.4 MB/s 
     |████████████████████████████████| 449 kB 49.5 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=bf740258b1a56094bbc0d6cd3f32052efb650fab61c7a3356a676a3adafbcd4c
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Succes

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.0.0'

### Constantes
O tensorflow trabalha facilmente com matrizes, de forma muito parecida com o Numpy, uma outra biblioteca pytho que você depode conhecer netse [link](https://numpy.org/)

#### Definindo uma constante

Vamos agora criar uma matriz constante, com os seguintes elementos:
$$
\begin{bmatrix}
23 & 4\\
32 & 51
\end{bmatrix}
$$

In [6]:
# Definindo uma constante no TensorFlow 2.0
tensor = tf.constant([[23, 4], [32, 51]])

In [7]:
tensor

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
# Acessando as dimensões de um tensor
tensor.shape

TensorShape([2, 2])

#### Acessando os valores de uma constante

In [9]:
# Acessando os valores de um tensor com o numpy e sem precisar de uma sessão
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [10]:
print(tensor[0,0])
print(tensor[0,1])
print(tensor[1,0])
print(tensor[1,1])

tf.Tensor(23, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(51, shape=(), dtype=int32)


In [11]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_tensor = np.array([[23,  4], [32, 51]])

In [12]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [13]:
tensor_from_numpy

<tf.Tensor: id=17, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [14]:
print(tensor_from_numpy[0,0])
print(tensor_from_numpy[0,1])
print(tensor_from_numpy[1,0])
print(tensor_from_numpy[1,1])

tf.Tensor(23, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(32, shape=(), dtype=int64)
tf.Tensor(51, shape=(), dtype=int64)


Essa facilidade de trabalhar com arrays do numpy diretamente no tensorflow vai ser muito ultil principalmente para quem já trabalha com outras biblioteca machine learning como o [scikit-learn](https://scikit-learn.org/stable/)

### Variáveis

#### Definindo uma variável
Vamos agora criar uma varíavel, usando a seguinte matriz:
$$
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{bmatrix}
$$

In [15]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Acessando os valores de uma variável

In [16]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [17]:
print(tf2_variable.numpy()[0,0])
print(tf2_variable.numpy()[0,1])
print(tf2_variable.numpy()[0,1])
print(tf2_variable.numpy()[1,0])
print(tf2_variable.numpy()[1,1])
print(tf2_variable.numpy()[1,1])

1.0
2.0
2.0
4.0
5.0
5.0


#### Alterando um valor específico de uma variável

Para alterar um valor espefico de uma variável, usamos o método àssign()`com a seguinte sintaxe:  

**`variavel[linha, coluna].assing(novo valor)`**

In [18]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [19]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### Operações com tensores

também podemos fazer operações com tensores, comecemos pelas operações com escalares usando:
$$
tensor = \begin{bmatrix}
1 & 2\\ 
3 & 4
\end{bmatrix}
$$

In [20]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=58, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Adição entre um escalar e um tensor

Vamos realizar a operação

$$
tensor + 5 = \begin{bmatrix}
1 & 2\\ 
3 & 4
\end{bmatrix} + 5 = \begin{bmatrix}
6 & 7\\ 
8 & 9
\end{bmatrix}
$$

In [21]:
tensor + 5

<tf.Tensor: id=60, shape=(2, 2), dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>

#### Multiplicação entre um escalar e um tensor

Agora vamos realizar a operação

$$
tensor \cdot 5 = \begin{bmatrix}
1 & 2\\ 
3 & 4
\end{bmatrix} \cdot 5 = \begin{bmatrix}
5 & 10\\ 
15 & 20
\end{bmatrix}
$$

In [22]:
tensor * 5

<tf.Tensor: id=62, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Usando funções do numpy nos tensores do TensorFlow

Também podemos aplicar funções do numpy aos tensores por exemplo:

$$
tensor^2 = \begin{bmatrix}
1^2 & 2^2\\ 
3^2 & 4^2
\end{bmatrix} \cdot 5 = \begin{bmatrix}
1 & 4\\ 
9 & 16
\end{bmatrix}
$$


In [23]:
# Obtendo o quadrado de todos os membros de um tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [24]:
# Obtendo a raiz quadrada de todos os membros de um tensor
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product (produto escalar) entre dois tensores

Vamos agora fazer o produto de duas matrizes, temos a matriz tensor:
$$
tensor = \begin{bmatrix} 1 & 2\\ 3 & 4 \end{bmatrix}
$$
e a matris tensor20:
$$
tensor20 = \begin{bmatrix} 23 & 4\\  32 & 51 \end{bmatrix} 
$$
Portanto teriámos o produto de tensor e tensor20 que seria:
$$
\begin{bmatrix} 1 & 4\\ 9 & 16 \end{bmatrix} \cdot  \begin{bmatrix} 23 & 4\\  32 & 51 \end{bmatrix} =  \begin{bmatrix} 87 & 106\\  197 & 216 \end{bmatrix}
$$ 

In [25]:
tensor

<tf.Tensor: id=58, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [26]:
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20

<tf.Tensor: id=63, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [27]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Strings no TensorFlow 2.0

Também podemos trabalhar com strigs, por enquanto vamos ficar no básico vamos ver como criar uma constante

In [28]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=64, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operações simples com strings

podemos deterninar a qualtidade de caracteres de uma string usando o método .`strings.length()`, gerar uma versão com todos os caracteres com maiúsculas com `strings.upper()` e com todos os caracteres em minúsculas usando `strings.lower()`  

In [ ]:
tf.strings.length(tf_string)

<tf.Tensor: id=107, shape=(), dtype=int32, numpy=10>

In [ ]:
tf.strings.upper(tf_string)

<tf.Tensor: id=108, shape=(), dtype=string, numpy=b'TENSORFLOW'>

In [ ]:
tf.strings.lower(tf_string)

<tf.Tensor: id=109, shape=(), dtype=string, numpy=b'tensorflow'>

#### Armazenando arrays (vetores) de strings

também podemos trabalhar com vetores de strings, bem como interagir sobre eles de formas bem conhecidas para quem já está trabalhando no Python Básico.

In [30]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [31]:
# Iterating through the TF string array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


## Conclusão
Neste breve tutorial vimos alguns apsectos inciais sobre o tensorflow, como instalação, constantes, variáveis, sua relação com o Numpy, operações báscias com matrizes e strings. Nos próximos tutoriais vamos iniciar o uso do tensorflow em machine learning, até lá!